# Generated by Django 5.1.6 on 2025-02-13 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(choices=[('base', 'Base'), ('extra', 'Extra')], max_length=50)),
                ('sub_group', models.CharField(choices=[('rice', 'Rice'), ('swallow', 'Swallow'), ('soup', 'Soup'), ('protein', 'Protein'), ('sides', 'Sides'), ('other', 'Other')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)])),
                ('meal_type', models.CharField(choices=[('sahoor', 'Sahoor'), ('iftar', 'Iftar')], max_length=10)),
                ('base_food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_meals', to='src.food')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.device')),
                ('extras', models.ManyToManyField(related_name='extras', to='src.food')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
