# Generated by Django 5.1.6 on 2025-02-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='device',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='base_food',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='day',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='unique_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='group',
            field=models.CharField(choices=[('base', 'Base'), ('extras', 'Extra')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
